# Generated by Django 3.2.16 on 2022-12-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationoption',
            old_name='variation',
            new_name='variation_id',
        ),
    ]
