# Generated by Django 3.2.16 on 2022-12-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_variation_variationoption_variation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(to='product.VariationOption'),
        ),
        migrations.DeleteModel(
            name='Configiraton',
        ),
    ]
