# Generated by Django 3.2.16 on 2022-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20221218_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
        migrations.AddField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(to='product.VariationOption'),
        ),
    ]
