# Generated by Django 3.2.16 on 2022-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('district', models.CharField(max_length=45)),
                ('neighborhood', models.CharField(blank=True, max_length=45, null=True)),
                ('adress_line', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
