# Generated by Django 3.2.16 on 2022-12-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=0)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.adress')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='user_Adresses',
            field=models.ManyToManyField(through='user.Person_adresses', to='user.Adress'),
        ),
    ]
