# Generated by Django 3.2.16 on 2022-12-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20221221_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_Adresses',
            new_name='user_adresses',
        ),
    ]
