# Generated by Django 3.2.16 on 2022-12-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20221222_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_card',
            name='user',
        ),
        migrations.AddField(
            model_name='credit_card',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
    ]
