# Generated by Django 3.2.16 on 2022-12-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_price'),
        ('user', '0010_auto_20221222_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_card_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(through='user.Shopping_card_items', to='product.Item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
        ),
        migrations.AddField(
            model_name='shopping_card_items',
            name='Shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shopping_cart'),
        ),
        migrations.AddField(
            model_name='shopping_card_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
    ]
