# Generated by Django 3.2.16 on 2022-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20221222_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_adresses',
            name='is_default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
