# Generated by Django 3.2.16 on 2022-12-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_person_adresses_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_adresses',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
