# Generated by Django 3.2.16 on 2022-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_price'),
        ('user', '0013_alter_person_adresses_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_favorites',
            field=models.ManyToManyField(to='product.Item'),
        ),
    ]
