# Generated by Django 3.2.16 on 2022-12-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_price'),
        ('user', '0014_person_user_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_basket_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('Shopping_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shopping_basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shopping_card_items',
        ),
        migrations.DeleteModel(
            name='Shopping_cart',
        ),
        migrations.AddField(
            model_name='shopping_basket',
            name='items',
            field=models.ManyToManyField(through='user.Shopping_basket_items', to='product.Item'),
        ),
        migrations.AddField(
            model_name='shopping_basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
    ]
