# Generated by Django 3.2.16 on 2022-12-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_price'),
        ('user', '0015_auto_20221224_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_basket',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, through='user.Shopping_basket_items', to='product.Item'),
        ),
        migrations.AlterField(
            model_name='shopping_basket_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.item'),
        ),
    ]
