# Generated by Django 3.2.16 on 2022-12-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20221224_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_basket_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
