# Generated by Django 3.2.16 on 2022-12-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_alter_shopping_basket_items_quantity'),
        ('product', '0009_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_total', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.person')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.item')),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_order.shoporder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], max_length=45, null=True)),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_order.shoporder')),
            ],
        ),
    ]
