# Generated by Django 3.2.16 on 2022-12-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], default='In Progress', max_length=45, null=True),
        ),
    ]
