# Generated by Django 3.2.16 on 2022-12-27 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0002_alter_orderstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='shop_order',
        ),
        migrations.AddField(
            model_name='shoporder',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_order.orderstatus'),
        ),
    ]
