# Generated by Django 3.2.16 on 2022-12-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0003_auto_20221227_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoporderitems',
            name='shop_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='shop_order.shoporder'),
        ),
    ]
